# Generated by Django 5.2.3 on 2025-07-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlephoto',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
